version: "3.9"
services:
  postgres:
    image: postgres:15
    container_name: wordfinderpostgres
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=words
