name: Word Finder

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  GRADLE_OPTS: -Dorg.gradle.jvmargs="-Xmx6g -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8"

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Check-out code
        uses: actions/checkout@v3
      - name: Install Java toolchain
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17
      - name: Build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build --full-stacktrace
        working-directory: ./jvm/word-finder
